contents:
  packages:
    - tzdata
    - ca-certificates-bundle
    - traefik-3.5@local

entrypoint:
  command: /usr/bin/traefik

accounts:
  run-as: 65532
  users:
    - uid: 65532
      username: traefik
  groups:
    - gid: 65532
      groupname: traefik

paths:
  - path: /etc/traefik
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

  - path: /var/lib/traefik
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

work-dir: /var/lib/traefik

annotations:
  org.opencontainers.image.title: traefik
  dev.chainguard.package.main: traefik-3.5
